version: '3.9'

services:
  fastapi:
    image: kimjinbum/simhae-fastapi:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - shared-network

networks:
  shared-network:
    external: true