name: SIMHAE CI/CD

on:
  push:
    branches:
      - develop

jobs:
  build-deploy:
    if: github.repository == 'bum0w0/2025_SEASONTHON_TEAM_38_BE_2' || github.repository == 'YUSEONU/2025_SEASONTHON_TEAM_38_BE_2'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/simhae-fastapi:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/2025_SEASONTHON_TEAM_38_BE_2
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env
            echo "VECTOR_DB_DIR=/home/ec2-user/vector_store" >> .env
            export RDS_ENDPOINT=${{ secrets.RDS_ENDPOINT }}
            export DB_USERNAME=${{ secrets.DB_USERNAME }}
            export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            docker-compose pull
            docker-compose up -d
